import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Sidenav from "@/components/dashboard/sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidenav />
        {children}
        <SpeedInsights />
      </body>
    </html>
  );
}
